2025-04-13 04:40:58,132 INFO    MainThread:2940751 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/guswls/EEN4015_Intro2ML/pbl-2/wandb/run-20250413_044058-j0yzze8k/logs/debug.log
2025-04-13 04:40:58,133 INFO    MainThread:2940751 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/guswls/EEN4015_Intro2ML/pbl-2/wandb/run-20250413_044058-j0yzze8k/logs/debug-internal.log
2025-04-13 04:40:58,133 INFO    MainThread:2940751 [wandb_init.py:monkeypatch_ipython():581] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1628188150>
2025-04-13 04:40:58,133 INFO    MainThread:2940751 [wandb_init.py:init():781] calling init triggers
2025-04-13 04:40:58,133 INFO    MainThread:2940751 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-13 04:40:58,133 INFO    MainThread:2940751 [wandb_init.py:init():809] starting backend
2025-04-13 04:40:58,133 INFO    MainThread:2940751 [wandb_init.py:init():813] sending inform_init request
2025-04-13 04:40:58,135 INFO    MainThread:2940751 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-13 04:40:58,135 INFO    MainThread:2940751 [wandb_init.py:init():823] backend started and connected
2025-04-13 04:40:58,149 INFO    MainThread:2940751 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-04-13 04:40:58,149 INFO    MainThread:2940751 [wandb_run.py:_label_probe_notebook():1277] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-13 04:40:58,149 INFO    MainThread:2940751 [wandb_init.py:init():915] updated telemetry
2025-04-13 04:40:58,160 INFO    MainThread:2940751 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-13 04:40:58,720 INFO    MainThread:2940751 [wandb_init.py:init():1014] starting run threads in backend
2025-04-13 04:40:58,957 INFO    MainThread:2940751 [wandb_run.py:_console_start():2454] atexit reg
2025-04-13 04:40:58,957 INFO    MainThread:2940751 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-13 04:40:58,957 INFO    MainThread:2940751 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-13 04:40:58,958 INFO    MainThread:2940751 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-13 04:40:58,958 INFO    MainThread:2940751 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-13 04:40:58,959 INFO    MainThread:2940751 [wandb_run.py:_config_callback():1327] config_cb None None {'model': 'resnet18', 'batch_size': 128, 'num_epochs': 100, 'learning_rate': 0.001, 'optimizer': 'Adam', 'seed': 2025, 'deterministic': False, 'patience': 10, 'train_ratio': 0.8, 'val_ratio': 0.1, 'test_ratio': 0.1, 'cutmix_alpha': 1.0, 'cutmix_prob': 0.5}
2025-04-13 04:41:01,680 INFO    MainThread:2940751 [wandb_watch.py:_watch():71] Watching
2025-04-13 04:43:43,070 INFO    MainThread:2940751 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-13 04:43:43,070 INFO    MainThread:2940751 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-13 05:41:40,562 INFO    MainThread:2940751 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [wandb_run.py:_finish():2189] finishing run sokjh1310-hanyang-university/PBL-2/j0yzze8k
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [jupyter.py:save_history():460] not saving jupyter history
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [jupyter.py:save_ipynb():384] not saving jupyter notebook
2025-04-13 05:41:40,584 INFO    MainThread:2940751 [wandb_init.py:_jupyter_teardown():563] cleaning up jupyter logic
2025-04-13 05:41:40,585 INFO    MainThread:2940751 [wandb_run.py:_atexit_cleanup():2419] got exitcode: 0
2025-04-13 05:41:40,585 INFO    MainThread:2940751 [wandb_run.py:_restore():2401] restore
2025-04-13 05:41:40,585 INFO    MainThread:2940751 [wandb_run.py:_restore():2407] restore done
2025-04-13 05:41:52,867 WARNING MainThread:2940751 [wandb_init.py:init():1534] [no run ID] interrupted
Traceback (most recent call last):
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1530, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 799, in init
    wandb.run.finish()
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 483, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 425, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2182, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2204, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2431, in _atexit_cleanup
    self._on_finish()
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2690, in _on_finish
    wait_with_progress(
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guswls/.local/lib/python3.11/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 451, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.11/threading.py", line 327, in wait
    waiter.acquire()
KeyboardInterrupt
2025-04-13 05:41:54,609 INFO    MsgRouterThr:2940751 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 11 handles.
